name: Deploy app

on:
  push:
    branches:
      -master

jobs:
  create-deploy-artifacts
    name: Create Deployment Artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Compile Css and Javascript
        run:
            npm install
            npm run production